OnlineBridge/conv_cards/views.py
import os
from flask import Blueprint, request, render_template, redirect, url_for, flash, abort
from OnlineBridge import db, CONV_CARD_FOLDER
from flask_user import current_user, login_required, roles_required
from OnlineBridge.users.models import Member
from OnlineBridge.conv_cards.models import ConvCard
from OnlineBridge.conv_cards.forms import NewCardForm, SearchPlayerForm, ConfDeleteForm, ReplaceCardForm
from math import ceil
from datetime import datetime

conv_cards = Blueprint('conv_cards', __name__, template_folder='templates/conv_cards')

@conv_cards.route('/new_card', methods=['GET', 'POST'])
@login_required
def new_card():
    form = NewCardForm()

    # get all the players with whom the current user has already cards stored
    exclude_ids = [current_user.member.id]
    for card in current_user.member.my_cards:
        for player in card.players:
            exclude_ids.append(player.id)
    exclude_ids = set(exclude_ids)

    if request.method == "POST" and form.validate_on_submit():
        if form.partner_found:
            if form.partner_found.id in exclude_ids:
                flash('Mit diesem Partner hast du schon eine Konventionskarte abgelegt', 'error')

            elif 'conv_card' not in request.files:
                flash('Fileanhang fehlt', 'error')

            else:
                file = request.files['conv_card']

                # new convention card
                conv_card = ConvCard()
                conv_card.players.append(current_user.member)
                conv_card.players.append(form.partner_found)

                # save to database
                db.session.add(conv_card)
                db.session.commit()

                # save file
                file.save(os.path.join(CONV_CARD_FOLDER, conv_card.filename))

                return redirect(url_for('conv_cards.list_cards'))

    possible_partners = Member.query.filter(Member.id.notin_(exclude_ids)).\
        order_by(Member.last_name.asc(), Member.first_name.asc()).all()

    context = {
        'form': form,
        'possible_partners': possible_partners
    }

    return render_template('new_card.html', **context)


@conv_cards.route('/list_cards')
@login_required
def list_cards():
    per_page = 8

    # get arguments
    page = request.args.get('page', 1, type=int)
    slug = request.args.get('slug', '', type=str)

    own_cards = True

    # retrieve player
    if slug == '':
        member = current_user.member
    else:
        if not current_user.has_roles('Director'):
            abort(403)
        own_cards = False
        per_page = 15
        member = Member.query.filter_by(slug=slug).first_or_404()

    # retrieve partners
    partners = []
    for card in member.my_cards:
        for player in card.players:
            if player.id != member.id:
                partners.append({'list_name': player.list_name, 'card': card})

    partners.sort(key=lambda p:p['list_name'])

    # prepare pagination
    num_pages = ceil(len(partners) / per_page)
    page = min(page, num_pages)
    page = max(page, 1)
    if len(partners) > 0:
        partners = partners[(page-1)*per_page:page*per_page]

    pages = range(1, num_pages+1)

    context = {
        'pages': pages,
        'page': page,
        'partners': partners,
        'player': member,
        'own_cards': own_cards,
        'num_pages': num_pages,
        'slug': slug
    }
    return render_template('list_cards.html', **context)


@conv_cards.route('/search_player', methods=['GET', 'POST'])
@roles_required('Director')
def search_player():
    if ConvCard.query.count() == 0:
        flash('Noch keine Konventionskarten vorhanden', category='info')
        return redirect(url_for('core.index'))

    form = SearchPlayerForm()
    if request.method == "POST" and form.validate_on_submit():
        return redirect(url_for('conv_cards.list_cards', slug=form.player_found.slug))

    # get players with convention cards
    players = []
    for card in ConvCard.query.all():
        for player in card.players:
            players.append(player.id)

    players = set(players)

    card_players = Member.query.filter(Member.id.in_(players)).\
        order_by(Member.last_name.asc(), Member.first_name.asc()).all()

    context = {
        'form': form,
        'players': card_players
    }
    return render_template('search_player.html', **context)


@conv_cards.route('/<string:slug>/<pl_slug>/conf_delete', methods=['GET', 'POST'])
@roles_required('Superuser')
def conf_delete(slug, pl_slug):
    card = ConvCard.query.filter_by(slug=slug).first_or_404()

    form = ConfDeleteForm()

    if request.method == "POST" and form.validate_on_submit():
        filename = card.filename

        db.session.delete(card)
        db.session.commit()

        os.remove(os.path.join(CONV_CARD_FOLDER, filename))

        flash('Karte gelöscht', 'success')
        return redirect(url_for('conv_cards.list_cards', slug=pl_slug))

    return render_template('conf_delete.html', form=form, card=card, pl_slug=pl_slug)


@conv_cards.route('/<string:slug>/detail', methods=['GET', 'POST'])
@login_required
def detail(slug):
    card = ConvCard.query.filter_by(slug=slug).first_or_404()
    if current_user.member not in card.players:
        abort(403)

    form = ReplaceCardForm()

    if request.method == "POST" and form.validate_on_submit():
        if 'conv_card' not in request.files:
            flash('Fileanhang fehlt', 'error')

        else:
            file = request.files['conv_card']

            # save to database
            card.uploaded = datetime.now()
            db.session.add(card)
            db.session.commit()

            # save file
            file.save(os.path.join(CONV_CARD_FOLDER, card.filename))

            flash('Karte ersetzt', 'success')
            return redirect(url_for('conv_cards.detail', slug=slug))

    context = {
        'form': form,
        'card': card
    }

    return render_template('detail.html', **context)


@conv_cards.route('/<string:slug>/delete', methods=['GET'])
@login_required
def delete(slug):
    card = ConvCard.query.filter_by(slug=slug).first_or_404()
    if current_user.member not in card.players:
        abort(403)

    filename = card.filename

    db.session.delete(card)
    db.session.commit()

    os.remove(os.path.join(CONV_CARD_FOLDER, filename))

    flash('Karte gelöscht', 'success')
    return redirect(url_for('conv_cards.list_cards'))

OnlineBridge/conv_cards/templates/conv_cards/conf_delete.html
{% extends 'base.html' %}

{% block content %}
  <div class="jumbotron">
    <h1>
      Löschen der Konventionskarte bestätigen
    </h1>
  
    <h5 class="mt-3">
      {% for player in card.players %}
        {{ player.first_name }} {{ player.last_name }}{% if loop.index0 == 0 %} - {% endif %}

      {% endfor %}

    </h5>

    <form class="form mt-3" method="post" role="form">
      {{ form.hidden_tag() }}
      {{ wtf.form_errors(form, hiddens='only') }}

      {{ wtf.form_field(form.submit, button_map={'submit':'danger'}) }}

      <a class="btn btn-dark ml-2" href="{{ url_for('conv_cards.list_cards', slug=pl_slug) }}" role="button">Zurück</a>
    </form>

    <p class="mt-3">Gegebenenfalls auch den Account sperren</p>

{% endblock %}

OnlineBridge/conv_cards/templates/conv_cards/detail.html
{% extends 'base.html' %}

{% block content %}
  <div class="jumbotron">
    <h1>
      Partner
      {% for player in card.players %}
        {% if player != current_user.member %}
          {{ player.first_name }} {{ player.last_name }}
        {% endif %}
      {% endfor %}
    </h1>
  
    <h5 class="mt-3">
      Hochgeladen am {{ card.uploaded.strftime('%d.%m.%Y um %H:%M Uhr') }}.
    </h5>

    <p>
      Mit einem Rechtsklick auf <em>Anzeigen</em> öffnet sich ein Kontextmenü, in dem du die Adresse kopieren kannst.
      Diese kannst du anschließend in den Chat einfügen und so den Gegnern zur Verfügung stellen.
    </p>

      <a class="btn btn-primary" href="{{ url_for('static', filename='conv_cards/'+card.filename) }}" target="_blank"
         role="button">Anzeigen</a>

      <button type="button" class="btn btn-danger ml-2 " data-toggle="modal" data-target="#DelModal">
        Löschen
      </button>
      <a class="btn btn-dark ml-2" href="{{ url_for('conv_cards.list_cards', page=page) }}" role="button">Zurück</a>

    {{ wtf.quick_form(form, extra_classes=' mt-5 ', button_map={'submit':'primary'}) }}


{#    <!-- Modalfor confirm delete -->#}
    <div class="modal fade" id="DelModal" tabindex="-1" aria-labelledby="DelModal" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Löschen bestätigen</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            Die Karte wirklich löschen?
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Abbrechen</button>
            <form action="{{ url_for('conv_cards.delete', slug=card.slug) }}" method="get">
              <button type="submit" class="btn btn-danger">Löschen</button>
            </form>
          </div>
        </div>
      </div>
    </div>
{% endblock %}

OnlineBridge/conv_cards/templates/conv_cards/list_cards.html
{% extends 'base.html' %}

{% block content %}
  <div class="jumbotron">
    <h1>
      {% if own_cards %}
        Meine Konventionskarten
      {% else %}
        Konventionskarten von {{ player.first_name }} {{ player.last_name }}
      {% endif %}
    </h1>

    {% if own_cards %}
      <a href="{{ url_for('conv_cards.new_card') }}" class="mt-3 btn btn-primary">Neue Karte</a>
      <p class="mt-3">Durch Klick auf den Namen des Partners wird die Konventionskarte angezeigt,
      mit einem Rechtsklick öffnet sich ein Kontextmenü, in dem du die Adresse kopieren kannst.
      Diese kannst du anschließend in den Chat einfügen und so den Gegnern zur Verfügung stellen.</p>

    {% endif %}

  </div>

  {% for partner in partners %}
    <div class="row {{ loop.cycle('bg-light', 'bg-transparent') }}">
      <div class="col-7">
        <a href="{{ url_for('static', filename='conv_cards/'+partner['card'].filename) }}" target="_blank" class="text-reset">
          {{ partner['list_name'] }}
        </a>
      </div>

      <div class="col text-right">
        {% if current_user.has_roles('Superuser') and not own_cards %}
          <a href="{{ url_for('conv_cards.conf_delete', slug=partner['card'].slug, pl_slug=slug) }}" class="text-reset">Löschen</a>
        {% elif own_cards %}
          <a href="{{ url_for('conv_cards.detail', slug=partner['card'].slug) }}" class="text-reset">Ändern / Löschen</a>
        {% endif %}

      </div>
    </div>
  {% else %}
    <div class="row">
      <div class="col">
        Keine Konventionskarten gefunden
      </div>
    </div>
  {% endfor %}


<nav aria-label='cards aria' class="mt-2">
  <ul class="pagination justify-content-center">
    {% for page_num in pages  %}
        <li class='page-item {% if page == page_num %}disabled{% endif %}'>
          <a class="page-link" href="{{ url_for('conv_cards.list_cards',page=page_num, slug=slug) }}">{{ page_num}}</a>
        </li>
    {% endfor %}
  </ul>

</nav>


{% endblock %}

OnlineBridge/conv_cards/templates/conv_cards/new_card.html
{% extends 'base.html' %}

{% block content %}
  <div class="jumbotron">
    <h1>Neue Konventionskarte</h1>

    <p class="mt-3">
      Pro Partnerschaft könnt ihr ein PDF Dokument hinterlegen.
      Vorlagen findest du zum Beispiel auf den Homepages des
      <a href="https://www.bridgeaustria.at/bridgedownloads/konventionskarten/" target="_blank">ÖBV</a> oder der
      <a href="http://www.worldbridge.org/rules-regulations/competitions/wbf-convention-card-editors/" target="_blank">WBF</a>.
    </p>
    <p>
      Um den Partner zu wählen, schreib einfach einen beliebigen Teil seines Namens und wähl ihn dann aus der Liste,
      die sich öffnet, sodass er komplett mit der Kennung im Feld steht.
    </p>

    {{ wtf.quick_form(form, extra_classes=' mt-3 ', button_map={'submit':'primary'}) }}

  </div>

  <datalist id="memberlist">
    {% for possible_partner in possible_partners %}
      <option>
        {{ possible_partner.last_name }} {{ possible_partner.first_name }}
        {% if possible_partner.fed_nr %}
          {{ possible_partner.fed_nr }}
        {% else %}
          {{ possible_partner.guest_nr }}
        {% endif %}
      </option>

    {% endfor %}

  </datalist>
{% endblock %}

OnlineBridge/conv_cards/templates/conv_cards/search_player.html
{% extends 'base.html' %}

{% block content %}
  <div class="jumbotron">
    <h1>Konventionskarten für einen Spieler anzeigen</h1>

    <p class="mt-3">
      Um den Spieler zu wählen, schreib einfach einen beliebigen Teil seines Namens und wähl ihn dann aus der Liste,
      die sich öffnet, sodass er komplett mit der Kennung im Feld steht.
    </p>

    {{ wtf.quick_form(form, extra_classes=' mt-3 ', button_map={'submit':'primary'}) }}

  </div>

  <datalist id="memberlist">
    {% for player in players %}
      <option>
        {{ player.last_name }} {{ player.first_name }}
        {% if player.fed_nr %}
          {{ player.fed_nr }}
        {% else %}
          {{ player.guest_nr }}
        {% endif %}
      </option>

    {% endfor %}

  </datalist>
{% endblock %}