OnlineBridge/tournadmin/views.py
# tournadmin
from flask import Blueprint,request, render_template, redirect, abort, flash, url_for
from flask_user import login_required, roles_required, current_user
from OnlineBridge import db
from OnlineBridge.tournadmin.models import VPScale, ScoringMethod, TimeDisplay
from OnlineBridge.tournadmin.forms import ParameterForm
from utilities import pagination_setup

tournadmin = Blueprint('tournadmin', __name__, template_folder='templates/tournadmin')

def get_param_model(param_type):
    model = None
    show_tourn_type = False
    param_type_str = None

    if param_type == 'vp_scale':
        model = VPScale
        param_type_str = ('VP Skala', 'VP Skalen', 'vp_scale')
    elif param_type == 'time_display':
        model = TimeDisplay
        param_type_str = ('Zeitanzeige', 'Zeitanzeigen', 'time_display')
    elif param_type =='scoring_method':
        model = ScoringMethod
        param_type_str = ('Scoremethode', 'Scoremethoden', 'scoring_method')
        show_tourn_type = True

    if model is None:
        abort(404)

    return model, param_type_str, show_tourn_type


@tournadmin.route('/parameter/<string:param_type>/new', methods=['GET', 'POST'])
@roles_required('Superuser')
def new_param(param_type):
    per_page = 10

    model, param_type_str, show_tourn_type = get_param_model(param_type)

    page, last_page = pagination_setup(per_page, model)

    form = ParameterForm(True, model, -1)

    if request.method == "POST" and form.validate_on_submit():
        parameter = model(id=form.id.data, name=form.name.data)
        if show_tourn_type:
            parameter.tournament_type = form.tournament_type.data

        db.session.add(parameter)
        db.session.commit()

        return redirect(url_for('tournadmin.new_param',param_type=param_type, page=page))

    parameters = model.query.order_by(model.id.asc()).paginate(page=page, per_page=per_page)

    context = {
        'form': form,
        'parameters': parameters,
        'show_tourn_type': show_tourn_type,
        'new_param': True,
        'param_type': param_type_str
    }
    return render_template('parameter.html', **context)


@tournadmin.route('/parameter/<string:param_type>/<int:id>/update', methods=['GET', 'POST'])
@roles_required('Superuser')
def update_paramm(param_type ,id):
    per_page = 10

    model, param_type_str, show_tourn_type = get_param_model(param_type)

    page, last_page = pagination_setup(per_page, model)

    parameter = model.query.filter_by(id=id).first_or_404()

    form = ParameterForm(False, model, parameter.id)

    if request.method == "POST" and form.validate_on_submit():
        parameter.name = form.name.data
        if show_tourn_type:
            parameter.tournament_type = form.tournament_type.data

        db.session.add(parameter)
        db.session.commit()

        return redirect(url_for('tournadmin.new_param', page=page, param_type=param_type))

    elif request.method == 'GET':
        form.name.data = parameter.name
        if show_tourn_type:
            form.tournament_type.data = parameter.tournament_type

    form.id.data = parameter.id
    parameters = model.query.order_by(model.id.asc()).paginate(page=page, per_page=per_page)

    context = {
        'form': form,
        'parameters': parameters,
        'this_param': parameter,
        'show_tourn_type': show_tourn_type,
        'new_param': False,
        'param_type': param_type_str
    }
    return render_template('parameter.html', **context)


@tournadmin.route('/parameter/<string:param_type>/<int:id>/delete', methods=['GET'])
@roles_required('Superuser')
def param_delete(param_type, id):
    if request.method == 'GET':
        model, param_type_str, show_tourn_type = get_param_model(param_type)

        parameter = model.query.filter_by(id=id).first_or_404()
        db.session.delete(parameter)
        db.session.commit()

    return redirect(url_for('tournadmin.new_param', param_type=param_type))

OnlineBridge/tournadmin/templates/tournadmin/parameter.html
{% extends 'base.html' %}

{% block content %}
  <div class="jumbotron">
    <h1>
      {% if new_param %}
        Neue {{ param_type[0] }}
      {% else %}
        {{ param_type[1] }}
      {% endif %}
    </h1>

    <form class="form" method="post" role="form">
      {{ form.hidden_tag() }}
      {{ wtf.form_errors(form, hiddens="only") }}

      <div class="form-row">
        <div class="col-2 col-lg-1">
          {{ wtf.form_field(form.id) }}
        </div>
        <div class="col">
          {{ wtf.form_field(form.name) }}
        </div>
      </div>

      {% if show_tourn_type %}
        <div class="btn-group btn-group-toggle mb-3" data-toggle="buttons">
          <label class="btn btn-secondary active">
            <input id="tournament_type-0" name="tournament_type" type="radio" value="P"
            {% if not new_param and this_param.tournament_type=='P' %} checked {% endif %}
            > Paar
          </label>
          <label class="btn btn-secondary">
            <input id="tournament_type-1" name="tournament_type" type="radio" value="T"
            {% if new_param or this_param.tournament_type=='T' %} checked {% endif %}
            > Team
          </label>
        </div>
        <br>
      {% endif %}

      {{ wtf.form_field(form.submit, button_map={'submit':'primary'}) }}

      {% if not new_param %}
        <button type="button" class="btn btn-danger ml-2 " data-toggle="modal" data-target="#DelModal">
          Löschen
        </button>

        <a class="btn btn-dark ml-2" href="{{ url_for('tournadmin.new_param', param_type=param_type[2]) }}" role="button">Zurück</a>
      {% endif %}

    </form>
  </div>

  {% for parameter in parameters.items %}
    <a href="{{ url_for('tournadmin.update_paramm', id=parameter.id, param_type=param_type[2]) }}" class="text-reset">
      <div class="row {{ loop.cycle('bg-light', 'bg-transparent') }}">
        <div class="col-2 col-lg-1">
          {{ parameter.id }}
        </div>
        <div class="col">
          {{ parameter.name }}
        </div>
      </div>
    </a>
  {% else %}
    <div class="row">
      <div class="col">
        Keine Einträge gefunden
      </div>
    </div>
  {% endfor %}



<nav aria-label='Guests aria' class="mt-2">
  <ul class="pagination justify-content-center">
    {% for page_num in parameters.iter_pages(left_edge=1,right_edge=1,left_current=2,right_current=3)  %}
      {% if page_num %}
        <li class='page-item {% if parameters.page == page_num %}disabled{% endif %}'>
          <a class="page-link" href="{{url_for('tournadmin.new_param', param_type=param_type[2], page=page_num)}}">{{ page_num}}</a>
          </li>
      {% else %}
        <li class='page-item disabled'>
          <span class="page-link">...</span>
        </li>
      {% endif %}
    {% endfor %}
  </ul>

</nav>


{#    <!-- Modalfor confirm delete -->#}
    <div class="modal fade" id="DelModal" tabindex="-1" aria-labelledby="DelModal" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Löschen bestätigen</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            {% if this_param %}
              Parameter {{ this_param.id }} {{ this_param.name }} wirklich löschen?
            {% endif %}

          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Abbrechen</button>
            {% if this_param %}
              <form action="{{ url_for('tournadmin.param_delete', id=this_param.id, param_type=param_type[2]) }}" method="get">
                <button type="submit" class="btn btn-danger">Löschen</button>
              </form>
            {% endif %}
          </div>
        </div>
      </div>
    </div>
{% endblock %}