OnlineBridge/admin/views.py
from flask import Blueprint, request, render_template, redirect, url_for, flash, abort
from flask_user import roles_required, current_user
from OnlineBridge.admin.forms import PlayerUploadForm, GuestDetailForm, UserDetailForm, CountryForm
from OnlineBridge.users.models import Member, User, Role
from OnlineBridge.admin.models import Club, Country
from OnlineBridge import db
from utilities.populate_db import fed_members_upload
from utilities import pagination_setup
from math import ceil

admin = Blueprint('admin', __name__, template_folder='templates/admin')

roles_as_str = ['Player', 'Director', 'Admin', 'Superuser']

@admin.route('/player_upload', methods=['GET', 'POST'])
@roles_required('Admin')
def player_upload():
    form = PlayerUploadForm()

    if request.method == 'POST' and form.validate_on_submit():
        success = False

        if 'player_file' in request.files:
            try:
                success = fed_members_upload(request.files['player_file'])
            except:
                pass

        if success:
            flash(u'Upload abgeschlossen', 'success')
        else:
            flash(u'Upload fehlgeschlagen', 'error')

        return redirect(url_for('core.index'))

    return render_template('oebv_players_upload.html', form=form)


@admin.route('/guests')
@roles_required('Admin')
def guests_page():
    per_page = 15
    page = request.args.get('page', 1, type=int)

    last_page = ceil(Member.query.filter(Member.guest_nr.isnot(None)).count() / per_page)

    page = min(page, last_page)
    page = max(page, 1)

    # Grab a list of guests from database.
    guests = Member.query.filter(Member.guest_nr.isnot(None)).\
        order_by(Member.last_name.asc()).paginate(page=page, per_page=per_page)
    return render_template('guests.html', guests=guests)


@admin.route('/guest/<slug>/update', methods=['GET', 'POST'])
@roles_required('Admin')
def guest_update(slug):
    form = GuestDetailForm(False)
    guest = Member.query.filter_by(slug=slug).one_or_none()
    if not guest:
        abort(404)

    if request.method == "POST" and form.validate_on_submit():
        guest.first_name = form.first_name.data.strip().title()
        guest.last_name = form.last_name.data.strip().title()

        db.session.add(guest)
        db.session.commit()

        return redirect(url_for('admin.guests_page'))

    elif request.method == 'GET':
        form.first_name.data = guest.first_name
        form.last_name.data = guest.last_name

    context = {
        'form': form,
        'new_guest': False,
        'guest': guest
    }

    return render_template('guest_detail.html', **context)


@admin.route('/guest/new', methods=['GET', 'POST'])
@roles_required('Admin')
def guest_new():
    form = GuestDetailForm(True)

    if request.method == "POST" and form.validate_on_submit():
        # get the next available number for a country
        next_nr = 1
        guests = Member.query.filter(Member.guest_nr.startswith(form.country_code.data)).all()

        if len(guests) > 0:
            nrs = [int(g.guest_nr[3:]) for g in guests]
            next_nr = max(nrs) + 1

        guest = Member(
            guest_nr=form.country_code.data.upper() + '{:04d}'.format(next_nr),
            first_name=form.first_name.data.strip().title(),
            last_name=form.last_name.data.strip().title()
        )

        db.session.add(guest)
        db.session.commit()

        return redirect(url_for('admin.guests_page'))

    # create datalist for choices
    ctry_codes = []
    guests = Member.query.filter(Member.guest_nr.isnot(None)).all()

    if len(guests) > 0:
        ctry_codes = [g.guest_nr[:3] for g in guests]

    ctry_codes.extend([c.code for c in Country.query.all()])

    ctry_codes = list(set(ctry_codes))
    ctry_codes.sort()

    context = {
        'form': form,
        'new_guest': True,
        'ctry_codes': ctry_codes
    }

    return render_template('guest_detail.html', **context)


@admin.route('/guest/<slug>/delete', methods=['GET'])
@roles_required('Admin')
def guest_delete(slug):

    guest = Member.query.filter_by(slug=slug).one_or_none()
    if not guest:
        abort(404)

    if request.method == "GET":

        db.session.delete(guest)
        db.session.commit()

    return redirect(url_for('admin.guests_page'))


@admin.route('/registered_users')
@roles_required('Superuser')
def registered_users():
    per_page = 15
    page = request.args.get('page', 1, type=int)

    last_page = ceil(User.query.filter(User.id.__ne__(current_user.id)).count() / per_page)

    page = min(page, last_page)
    page = max(page, 1)

    reg_users = User.query.filter(User.id.__ne__(current_user.id)).\
        order_by(User.last_name.asc(), User.first_name.asc()).paginate(page=page, per_page=per_page)

    all_users = User.query.filter(User.id.__ne__(current_user.id)).\
        order_by(User.last_name.asc(), User.first_name.asc()).all()

    context = {
        'reg_users': reg_users,
        'all_users': all_users,
        'roles_as_str': roles_as_str
    }

    return render_template('reg_users_list.html', **context)


@admin.route('/user_detail/<string:slug>/<int:page>', methods=['GET', 'POST'])
@roles_required('Superuser')
def user_detail(slug, page):
    user = User.query.filter_by(slug=slug).first_or_404()

    form = UserDetailForm()

    if request.method == "POST" and form.validate_on_submit():

        roles = []
        for r in roles_as_str:
            roles.append(Role.query.filter_by(name=r).one())

        user.roles = roles[:form.privileges.data]
        user.active = form.active.data

        db.session.add(user)
        db.session.commit()

        return redirect(url_for('admin.registered_users', page=page))

    elif request.method == 'GET':
        form.privileges.data = len(user.roles)
        print(len(user.roles))
        form.active.data = user.active

    context = {
        'user': user,
        'form': form,
        'page': page
    }

    return render_template('user_detail.html', **context)


@admin.route('/user/<slug>/delete<int:page>', methods=['GET'])
@roles_required('Superuser')
def user_delete(slug, page):

    if request.method == 'GET':
        reg_user = User.query.filter_by(slug=slug).one_or_none()
        if not reg_user:
            abort(404)

        db.session.delete(reg_user)
        db.session.commit()

    return redirect(url_for('admin.registered_users', page=page))


@admin.route('/get_user', methods=['GET'])
@roles_required('Superuser')
def get_user():

    page = request.args.get('page', 1, type=int)
    getuser = request.args.get('getuser', '', type=str)

    nr = getuser.split()[-1]

    if nr.isdigit():
        member = Member.query.filter_by(fed_nr=int(nr)).first_or_404()
    else:
        member = Member.query.filter_by(guest_nr=nr).first_or_404()

    if member.user.id == current_user.id:
        abort(403)

    return redirect(url_for('admin.user_detail', slug=member.user.slug, page=page))


@admin.route('/country/new', methods=['GET', 'POST'])
@roles_required('Superuser')
def new_country():
    per_page = 10

    page, last_page = pagination_setup(per_page, Country)

    form = CountryForm()

    if request.method == "POST" and form.validate_on_submit():
        country = Country(
            code=form.code.data.upper(),
            name=form.name.data.strip().title()
        )
        try:
            db.session.add(country)
            db.session.commit()

            return redirect(url_for('admin.new_country', page=page))
        except:
            db.session.rollback()
            flash('Code und Name müssen eindeutig sein', category='error')

    countries = Country.query.order_by(Country.code.asc()).paginate(page=page, per_page=per_page)

    context = {
        'form': form,
        'countries': countries,
        'new_country': True
    }
    return render_template('country.html', **context)


@admin.route('/country/<int:id>/update', methods=['GET', 'POST'])
@roles_required('Superuser')
def update_country(id):
    country = Country.query.filter_by(id=id).first_or_404()

    per_page = 10

    page, last_page = pagination_setup(per_page, Country)

    form = CountryForm()

    if request.method == "POST" and form.validate_on_submit():
        country.code = form.code.data.upper()
        country.name = form.name.data.strip().title()

        try:
            db.session.add(country)
            db.session.commit()

            return redirect(url_for('admin.new_country', page=page))
        except:
            db.session.rollback()
            flash('Code und Name müssen eindeutig sein', category='error')

    elif request.method == 'GET':
        form.code.data = country.code
        form.name.data = country.name

    countries = Country.query.order_by(Country.code.asc()).paginate(page=page, per_page=per_page)

    context = {
        'form': form,
        'countries': countries,
        'this_country': country,
        'new_country': False
    }
    return render_template('country.html', **context)


@admin.route('/country/<int:id>/delete', methods=['GET'])
@roles_required('Superuser')
def delete_country(id):

    if request.method == 'GET':
        country = Country.query.filter_by(id=id).first_or_404()

        db.session.delete(country)
        db.session.commit()

    return redirect(url_for('admin.new_country'))

OnlineBridge/conv_cards/views.py
import os
from flask import Blueprint, request, render_template, redirect, url_for, flash, abort
from OnlineBridge import db, CONV_CARD_FOLDER
from flask_user import current_user, login_required, roles_required
from OnlineBridge.users.models import Member
from OnlineBridge.conv_cards.models import ConvCard
from OnlineBridge.conv_cards.forms import NewCardForm, SearchPlayerForm, ConfDeleteForm, ReplaceCardForm
from math import ceil
from datetime import datetime

conv_cards = Blueprint('conv_cards', __name__, template_folder='templates/conv_cards')

@conv_cards.route('/new_card', methods=['GET', 'POST'])
@login_required
def new_card():
    form = NewCardForm()

    # get all the players with whom the current user has already cards stored
    exclude_ids = [current_user.member.id]
    for card in current_user.member.my_cards:
        for player in card.players:
            exclude_ids.append(player.id)
    exclude_ids = set(exclude_ids)

    if request.method == "POST" and form.validate_on_submit():
        if form.partner_found:
            if form.partner_found.id in exclude_ids:
                flash('Mit diesem Partner hast du schon eine Konventionskarte abgelegt', 'error')

            elif 'conv_card' not in request.files:
                flash('Fileanhang fehlt', 'error')

            else:
                file = request.files['conv_card']

                # new convention card
                conv_card = ConvCard()
                conv_card.players.append(current_user.member)
                conv_card.players.append(form.partner_found)

                # save to database
                db.session.add(conv_card)
                db.session.commit()

                # save file
                file.save(os.path.join(CONV_CARD_FOLDER, conv_card.filename))

                return redirect(url_for('conv_cards.list_cards'))

    possible_partners = Member.query.filter(Member.id.notin_(exclude_ids)).\
        order_by(Member.last_name.asc(), Member.first_name.asc()).all()

    context = {
        'form': form,
        'possible_partners': possible_partners
    }

    return render_template('new_card.html', **context)


@conv_cards.route('/list_cards')
@login_required
def list_cards():
    per_page = 8

    # get arguments
    page = request.args.get('page', 1, type=int)
    slug = request.args.get('slug', '', type=str)

    own_cards = True

    # retrieve player
    if slug == '':
        member = current_user.member
    else:
        if not current_user.has_roles('Director'):
            abort(403)
        own_cards = False
        per_page = 15
        member = Member.query.filter_by(slug=slug).first_or_404()

    # retrieve partners
    partners = []
    for card in member.my_cards:
        for player in card.players:
            if player.id != member.id:
                partners.append({'list_name': player.list_name, 'card': card})

    partners.sort(key=lambda p:p['list_name'])

    # prepare pagination
    num_pages = ceil(len(partners) / per_page)
    page = min(page, num_pages)
    page = max(page, 1)
    if len(partners) > 0:
        partners = partners[(page-1)*per_page:page*per_page]

    pages = range(1, num_pages+1)

    context = {
        'pages': pages,
        'page': page,
        'partners': partners,
        'player': member,
        'own_cards': own_cards,
        'num_pages': num_pages,
        'slug': slug
    }
    return render_template('list_cards.html', **context)


@conv_cards.route('/search_player', methods=['GET', 'POST'])
@roles_required('Director')
def search_player():
    if ConvCard.query.count() == 0:
        flash('Noch keine Konventionskarten vorhanden', category='info')
        return redirect(url_for('core.index'))

    form = SearchPlayerForm()
    if request.method == "POST" and form.validate_on_submit():
        return redirect(url_for('conv_cards.list_cards', slug=form.player_found.slug))

    # get players with convention cards
    players = []
    for card in ConvCard.query.all():
        for player in card.players:
            players.append(player.id)

    players = set(players)

    card_players = Member.query.filter(Member.id.in_(players)).\
        order_by(Member.last_name.asc(), Member.first_name.asc()).all()

    context = {
        'form': form,
        'players': card_players
    }
    return render_template('search_player.html', **context)


@conv_cards.route('/<string:slug>/<pl_slug>/conf_delete', methods=['GET', 'POST'])
@roles_required('Superuser')
def conf_delete(slug, pl_slug):
    card = ConvCard.query.filter_by(slug=slug).first_or_404()

    form = ConfDeleteForm()

    if request.method == "POST" and form.validate_on_submit():
        filename = card.filename

        db.session.delete(card)
        db.session.commit()

        os.remove(os.path.join(CONV_CARD_FOLDER, filename))

        flash('Karte gelöscht', 'success')
        return redirect(url_for('conv_cards.list_cards', slug=pl_slug))

    return render_template('conf_delete.html', form=form, card=card, pl_slug=pl_slug)


@conv_cards.route('/<string:slug>/detail', methods=['GET', 'POST'])
@login_required
def detail(slug):
    card = ConvCard.query.filter_by(slug=slug).first_or_404()
    if current_user.member not in card.players:
        abort(403)

    form = ReplaceCardForm()

    if request.method == "POST" and form.validate_on_submit():
        if 'conv_card' not in request.files:
            flash('Fileanhang fehlt', 'error')

        else:
            file = request.files['conv_card']

            # save to database
            card.uploaded = datetime.now()
            db.session.add(card)
            db.session.commit()

            # save file
            file.save(os.path.join(CONV_CARD_FOLDER, card.filename))

            flash('Karte ersetzt', 'success')
            return redirect(url_for('conv_cards.detail', slug=slug))

    context = {
        'form': form,
        'card': card
    }

    return render_template('detail.html', **context)


@conv_cards.route('/<string:slug>/delete', methods=['GET'])
@login_required
def delete(slug):
    card = ConvCard.query.filter_by(slug=slug).first_or_404()
    if current_user.member not in card.players:
        abort(403)

    filename = card.filename

    db.session.delete(card)
    db.session.commit()

    os.remove(os.path.join(CONV_CARD_FOLDER, filename))

    flash('Karte gelöscht', 'success')
    return redirect(url_for('conv_cards.list_cards'))

OnlineBridge/core/views.py
# under core
from flask import Blueprint, render_template

core = Blueprint('core', __name__, template_folder='templates/core')

@core.route('/')
def index():
    return render_template('index.html')

@core.route('/about')
def about():
    return render_template('about.html')

@core.route('/license')
def license():
    return render_template('license.html')

@core.route('/impressum')
def impressum():
    return render_template('impressum.html')

@core.route('/data_protection')
def data_protection():
    return render_template('ds.html')

@core.route('/user/reg_complete')
def reg_complete():
    return render_template('reg_compl.html')

@core.route('/user/password_reset')
def password_reset():
    return render_template('password_reset.html')

OnlineBridge/templates/base.html
<!DOCTYPE html>
{% import 'bootstrap/wtf.html' as wtf %}
<html lang="de">
<head>
  <meta charset="UTF-8">
  <title>Online Bridge</title>

{#  Bootstrap#}
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">

  <link rel="preconnect" href="https://fonts.gstatic.com">
  <link href="https://fonts.googleapis.com/css2?family=Roboto&display=swap" rel="stylesheet">

  <link rel="stylesheet" href="{{ url_for('static', filename='myStyles.css') }}">

{#  favicon #}
  <link rel="apple-touch-icon" sizes="57x57" href="{{ url_for('static', filename='images/apple-icon-57x57.png') }}">
  <link rel="apple-touch-icon" sizes="60x60" href="{{ url_for('static', filename='images/apple-icon-60x60.png') }}">
  <link rel="apple-touch-icon" sizes="72x72" href="{{ url_for('static', filename='images/apple-icon-72x72.png') }}">
  <link rel="apple-touch-icon" sizes="76x76" href="{{ url_for('static', filename='images/apple-icon-76x76.png') }}">
  <link rel="apple-touch-icon" sizes="114x114" href="{{ url_for('static', filename='images/apple-icon-114x114.png') }}">
  <link rel="apple-touch-icon" sizes="120x120" href="{{ url_for('static', filename='images/apple-icon-120x120.png') }}">
  <link rel="apple-touch-icon" sizes="144x144" href="{{ url_for('static', filename='images/apple-icon-144x144.png') }}">
  <link rel="apple-touch-icon" sizes="152x152" href="{{ url_for('static', filename='images/apple-icon-152x152.png') }}">
  <link rel="apple-touch-icon" sizes="180x180" href="{{ url_for('static', filename='images/apple-icon-180x180.png') }}">
  <link rel="icon" type="image/png" sizes="192x192"  href="{{ url_for('static', filename='images/android-icon-192x192.png') }}">
  <link rel="icon" type="image/png" sizes="32x32" href="{{ url_for('static', filename='images/favicon-32x32.png') }}">
  <link rel="icon" type="image/png" sizes="96x96" href="{{ url_for('static', filename='images/favicon-96x96.png') }}">
  <link rel="icon" type="image/png" sizes="16x16" href="{{ url_for('static', filename='images/favicon-16x16.png') }}">
  <link rel="manifest" href="{{ url_for('static', filename='images/manifest.json') }}">
  <meta name="msapplication-TileColor" content="#ffffff">
  <meta name="msapplication-TileImage" content="/ms-icon-144x144.png">
  <meta name="theme-color" content="#ffffff">
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark myNavBar">
  <a class="navbar-brand" href="{{ url_for('core.index') }}"><span class="myNavColor">Home</span></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">

      {% if current_user.is_authenticated and current_user.has_roles('Admin') %}
      <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true"
             aria-expanded="false">
            <span class="myNavColor">Admin</span>
          </a>
          <div class="dropdown-menu">
            {% if current_user.has_roles('Superuser') %}
              <a class="dropdown-item" href="{{ url_for('admin.registered_users') }}">registrierte Benutzer</a>
            {% endif %}
            <a class="dropdown-item" href="{{ url_for('admin.player_upload') }}">&Ouml;BV-Spieler importieren</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="{{ url_for('admin.guests_page') }}">G&auml;ste</a>

            {% if current_user.has_roles('Superuser') %}
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="{{ url_for('admin.new_country') }}">Staaten</a>
            {% endif %}

          </div>
        </li>
      {% endif %}

      {% if current_user.is_authenticated %}
      <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true"
             aria-expanded="false">
            <span class="myNavColor">Konventionskarten</span>
          </a>
          <div class="dropdown-menu">
            <a class="dropdown-item" href="{{ url_for('conv_cards.list_cards') }}">meine Karten</a>
            <a class="dropdown-item" href="{{ url_for('conv_cards.new_card') }}">neue Karte</a>
            {% if current_user.has_roles('Director') %}
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="{{ url_for('conv_cards.search_player') }}">Karten eines Spielers</a>
            {% endif %}
          </div>
        </li>
      {% endif %}

      {% if current_user.is_authenticated %}
      <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true"
             aria-expanded="false">
            <span class="myNavColor">Turnier</span>
          </a>
          <div class="dropdown-menu">
            {% if current_user.has_roles('Superuser') %}
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="{{ url_for('tournadmin.new_param', param_type='vp_scale') }}">VP-Skalen</a>
              <a class="dropdown-item" href="{{ url_for('tournadmin.new_param', param_type='time_display') }}">Zeitanzeigen</a>
              <a class="dropdown-item" href="{{ url_for('tournadmin.new_param', param_type='scoring_method') }}">Scoremethoden</a>
            {% endif %}
          </div>
        </li>
      {% endif %}
    </ul>

    <ul class="navbar-nav mr-4">
      <li class="nav-item dropdown mr-3">
        <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true"
           aria-expanded="false">
          <span class="myNavColor">
            {% if current_user.is_authenticated %}
              {{ current_user.first_name }}
            {% else %}
              Benutzer
            {% endif %}

          </span>
        </a>
        <div class="dropdown-menu">
          {% if current_user.is_authenticated %}
            <a class="dropdown-item" href="{{ url_for('user.edit_user_profile') }}">Profil</a>
            <a class="dropdown-item" href="{{ url_for('user.change_password') }}">Passwort ändern</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="{{ url_for('user.logout') }}">Abmelden</a>
          {% else %}
            <a class="dropdown-item" href="{{ url_for('user.login') }}">Anmelden</a>
            <a class="dropdown-item" href="{{ url_for('user.register') }}">Registrieren</a>
          {% endif %}
        </div>
      </li>

      <li class="nav-item">
        <a class="nav-link" href="{{ url_for('core.about') }}"><span class="myNavColor">About</span></a>
      </li>

    </ul>


  </div>
</nav>

<div class="container">

{% for mess in get_flashed_messages(with_categories=True)  %}
  <div class="alert
  {% if mess[0]=='success' %}
    alert-success
  {% elif mess[0]=='warning' %}
    alert-warning
  {% elif mess[0] in ['danger', 'error'] %}
    alert-danger
  {% elif mess[0]=='info' %}
    alert-info
  {% else %}
    alert-dark
  {% endif %}
  alert-dismissible fade show" role="alert">
    <button type="button" class="fade close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    {% if mess|length == 1 %}
       {{ mess | safe }}
    {% else %} 
      {{ mess[1] | safe }}
    {% endif %} 
    </div>
  {% endfor %}

  {% block content %}
  
  {% endblock %}
  
</div>

{% if not no_bottom_bar %}

  <nav class="navbar fixed-bottom navbar-dark myNavBar">

    <ul class="navbar-nav mr-auto">

      <li class="nav-item">
        <a class="nav-link" href="{{ url_for('core.license') }}"><span class="myNavColor">&copy;2021 Christian Bernscherer</span></a>
      </li>
    </ul>

    <ul class="navbar-nav flex-row mr-4">
      <li class="nav-item mr-2">
        <a class="nav-link" href="{{ url_for('core.impressum') }}"><span class="myNavColor">Impressum</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{{ url_for('core.data_protection') }}"><span class="myNavColor">Datenschutz</span></a>
      </li>
    </ul>

  </nav>

{% else %}

{% endif %}

{#Bootstrap#}
<script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.min.js" integrity="sha384-+YQ4JLhjyBLPDQt//I+STsc9iw4uQqACwlvpslubQzn4u2UU2UFM80nGisd026JF" crossorigin="anonymous"></script>
</body>
</html>